# Generated by Django 2.1.2 on 2018-12-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yazi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=120)),
                ('metin', models.TextField()),
                ('yayinTarihi', models.DateTimeField()),
            ],
        ),
    ]
